version: '2'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres-14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - spring
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.10.5-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
  eureka-server:
    image: 01062001/eureka-server:latest
    container_name: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    networks:
      - spring
    depends_on:
      - zipkin
  gateway:
    image: 01062001/gateway:latest
    container_name: gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8083"
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server
  customer:
    image: 01062001/customer:latest
    container_name: customer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server
      - db
      - rabbitmq
  fraud:
    image: 01062001/fraud:latest
    container_name: fraud
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server
      - db
  notification:
    image: 01062001/notification:latest
    container_name: notification
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server
      - db
      - rabbitmq

networks:
  spring:
    driver: bridge
